// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjluYa2RYrRM4hMDSbTwL_Isvq6kGoYvg',
    appId: '1:1022497136271:web:7d70f5904295387a15dafa',
    messagingSenderId: '1022497136271',
    projectId: 'touch-c3fb2',
    authDomain: 'touch-c3fb2.firebaseapp.com',
    storageBucket: 'touch-c3fb2.appspot.com',
    measurementId: 'G-91G7TFHR7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnLfrHHXzKyIBM_MPwnhdBVVGOyM1XQPI',
    appId: '1:1022497136271:android:c128102bc9c0517715dafa',
    messagingSenderId: '1022497136271',
    projectId: 'touch-c3fb2',
    storageBucket: 'touch-c3fb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCVYZtgaR5OIFSmpAf8VwydPGoTSvdT_0',
    appId: '1:1022497136271:ios:b78c2bef3940f56a15dafa',
    messagingSenderId: '1022497136271',
    projectId: 'touch-c3fb2',
    storageBucket: 'touch-c3fb2.appspot.com',
    iosBundleId: 'com.example.touch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCVYZtgaR5OIFSmpAf8VwydPGoTSvdT_0',
    appId: '1:1022497136271:ios:69abf91008d29af615dafa',
    messagingSenderId: '1022497136271',
    projectId: 'touch-c3fb2',
    storageBucket: 'touch-c3fb2.appspot.com',
    iosBundleId: 'com.example.touch.RunnerTests',
  );
}
